---
title: "Bio Inv Revisions"
author: "Caitlin Mothes, PhD"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(terra)
library(sf)
library(mapview)
library(spThin)
library(spdep)
```

# Read in Data

```{r}
## raw 10m landcover data
lc <- rast("data/landcover_mdc.tif")

## reclassify based on crosswalk doc

reclass <- read_csv("data/CLC_to_FNAINC_Crosswalk_20160701.csv")


land_reclass <- terra::classify(lc, as.matrix(reclass %>% dplyr::select(SITE, reclass)))
# values 2134 and 5300 in raster but not in table...
land_reclass[land_reclass == 5300] <- 16
land_reclass[land_reclass == 2134] <- 10

## read in occurrences

## COMBINE AND REMOVE DUPLICATES
### Agama
ag_all <- read_csv("data/agama_occ_mdc.csv") %>% select(LONG = Longitude, LAT = Latitude)

agama_pts <- read_csv("data/agama_sites.csv") %>% select(LONG, LAT) 

ag_combined <- bind_rows(ag_all, agama_pts) %>% distinct(LONG, LAT) %>% 
  mutate(species = "Agama")


### Basilisk
bas_all <- read_csv("data/basilisk_occ_mdc.csv") %>% select(LONG = Longitude, LAT = Latitude)

bas_pts <- read_csv("data/basilisk_sites.csv") %>% select(LONG, LAT)

bas_combined <- bind_rows(bas_all, bas_pts) %>% distinct(LONG, LAT) %>% 
 mutate(species = "Basilisk")

#mapview::mapview(bas_combined)

```

# Agama Land Cover Association

## Thin Points and clean

```{r}
## thin points (increasing thin.par as needed)
ag_thin <- thin(ag_combined, lat.col = "LAT", long.col = "LONG", spec.col = "species",
                thin.par = 0.25,
                reps = 50, write.files = FALSE, locs.thinned.list.return = TRUE)


## test for autocorrelation with join counts test, using last df
ag_thin_sf <- ag_thin[[50]] %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>% 
  st_transform(crs = st_crs(land_reclass))
```

## Set up for Join Counts test

```{r}
## create raster for test
r_ag <- rast(extent = ext(ag_thin_sf), resolution = 100, crs = crs(land_reclass))

r_ag2 <- rasterize(ag_thin_sf, r_ag, field = 1)
# make NA values 0
r_ag2[is.na(r_ag2)] <- 0

# check how many points were lost to rasterization at slightly larger res
freq(r_ag2) # none
```

## Run Join Counts Tests

```{r}
## set up connectivity matrix, rook default
nb <- cell2nb(nrow = nrow(r_ag2), ncol = ncol(r_ag2))

## convert to w weights list using Binary weights matrix
lwb <- nb2listw(nb, style = "B")

#join counts test and permuation test
ag_jc <- joincount.test(as.factor(values(r_ag2)), lwb, alternative = "greater")

ag_jc_perm <- joincount.mc(as.factor(values(r_ag2)), lwb, nsim = 999, alternative = "greater")


ag_jc
ag_jc_perm
```

## Recalculate LC Metrics

```{r}
ag_lc <- ag_thin_sf %>% 
  mutate(landcover = as.numeric(extract(lc, .)[[2]])) %>%
  left_join(reclass, by = c("landcover" = "SITE")) %>% 
  st_drop_geometry() %>% 
  count(NAME_STATE) %>% 
  # these calculations from Table 3 Metrics spreadsheet (from Chris)
  mutate(percent = n/sum(n)*100,
         point_estimate = (n+2)/(sum(n)+4),
         L95 = point_estimate-1.96*sqrt((point_estimate*(1-point_estimate))/(sum(n)+4)),
         U95 = point_estimate+1.96*sqrt((point_estimate*(1-point_estimate))/(sum(n)+4)),
         species = "Agama")


```

# Basilisk Land Cover Association

## Thin points and clean

```{r}
## thin points (increasing thin.par as needed)
bas_thin <- thin(bas_combined, lat.col = "LAT", long.col = "LONG", spec.col = "species",
                thin.par = 0.25,
                reps = 50, write.files = FALSE, locs.thinned.list.return = TRUE)


## test for autocorrelation with join counts test, using last df
bas_thin_sf <- bas_thin[[50]] %>%
  st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>% 
  st_transform(crs = st_crs(land_reclass))

```

## Set up for Join Counts Test

```{r}
## create raster for test
r_bas <- rast(extent = ext(bas_thin_sf), resolution = 100, crs = crs(land_reclass))

r_bas2 <- rasterize(bas_thin_sf, r_bas, field = 1)
# make NA values 0
r_bas2[is.na(r_bas2)] <- 0

# check how many points were lost to rasterization at slightly larger res
freq(r_bas2) # only 2

```

## Run Join Counts Test

```{r}
## set up connectivity matrix, rook default
nb <- cell2nb(nrow = nrow(r_bas2), ncol = ncol(r_bas2))

## convert to w weights list using Binary weights matrix
lwb <- nb2listw(nb, style = "B")

#join counts test and permuation test
bas_jc <- joincount.test(as.factor(values(r_bas2)), lwb, alternative = "greater")

bas_jc_perm <- joincount.mc(as.factor(values(r_bas2)), lwb, nsim = 999, alternative = "greater")


bas_jc
bas_jc_perm
```

## Recalc LC Metrics

```{r}
bas_lc <- bas_thin_sf %>% 
  mutate(landcover = as.numeric(extract(lc, .)[[2]])) %>%
  left_join(reclass, by = c("landcover" = "SITE")) %>% 
  st_drop_geometry() %>% 
  count(NAME_STATE) %>% 
  mutate(percent = n/sum(n)*100,
         point_estimate = (n+2)/(sum(n)+4),
         L95 = point_estimate-1.96*sqrt((point_estimate*(1-point_estimate))/(sum(n)+4)),
         U95 = point_estimate+1.96*sqrt((point_estimate*(1-point_estimate))/(sum(n)+4)),
         species = "Basilisk")


```

# Contingency Analysis

### Join datasets

```{r}
land_assoc <- bind_rows(ag_lc, bas_lc) %>% 
  filter(n >= 10) %>% 
  # filter to categories that have more than 10 for both species
  group_by(NAME_STATE) %>% 
  mutate(n_cats = n()) %>% 
  filter(n_cats > 1) %>% 
  ungroup() %>% 
  select(-n_cats)
  
```

### Contingency Analysis

```{r}

full_join(bas_lc, ag_lc, by = "NAME_STATE") %>%
  rename(bas_n = n.x, ag_n = n.y) %>%
  replace(is.na(.), 0) %>%
  #remove cover types with < 10 occ for both species
  filter(bas_n >= 10 | ag_n >= 10) %>% 
  column_to_rownames(var = "NAME_STATE") %>% select(bas_n, ag_n) %>% 
  chisq.test(.) 

#X-squared = 58.196, df = 8, p-value = 1.052e-09


```

### CI Analysis and Visual

```{r}
## confidence interval analysis

  
#assess CI overlap
land_assoc %>% 
ggplot(aes(x = species, y = point_estimate, color = species))+
  geom_point(size = 4)+
  geom_errorbar(aes(ymin = L95, ymax = U95))+
  scale_color_manual(name = "Species", values = c("blue", "red"))+
  ylab("Probability of Occurence")+
  theme_bw()+
  facet_wrap(~ NAME_STATE, nrow = 1, strip.position = "bottom")+
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "bottom")
```
